### ISSUE TITLE
Network upgrade / manage network lifecycle

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#140]
Introduce or improve commands to manage network lifecycle, for example:

- [ ] install new chaincode (it should install it in the network and update Fablo config file)
- [ ] upgrade chaincode (right now it can upgrade existing chaincode, but does not change Fablo config file)
- [ ] change MaxMessageCount or other config params (right now it is not possible for a running network; you can do it before network starts with hooks)
- [ ] Add channel (not possible for a running network)
- [ ] Change peer number (not possible for a running network)
- Remove channel/chaincode/org (not possible for a running network)

This comment is up to date with Fablo 1.1.0

**Comment by ramsey-dao-dmtp** [comment]
Hi @dzikowski , I'm looking for:

- Change peer number
- Remove channel/chaincode/org

Via Fablo-config.json file
Can the current version (1.1.0) can do this?

**Comment by dzikowski** [comment]
Unfortunately no. Right now we don't support many changes when the Fablo network is running. You can configure orgs, channels, chaincodes etc. before the network is started. I extended the initial comment to reflect the current state.

**Comment by dzikowski** [comment]
Closing: Cleanup of stale issues. Please reopen if needed.
