### ISSUE TITLE
Initial Kubernetes support

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#351]
Basic support is going to be released in version `1.2.0`.

Verify if the following features work for Kubernetes. Provide error message and GitHub issue if not (either in `fablo-k8s.sh`, `fablo.sh`, `_validateEngineSpecificSettings`):
- [ ] up, down, reset, start stop
- [ ] prune, recreate
- [ ] chaincode install/upgrade
- [ ] dev mode?
- [ ] TLS (won't be supported) - serve validation error @Hejwo 
- [ ] snapshot, restore
- [ ] Orderer - Solo or RAFT
- [ ] CA db - embedded or postgres
- [ ] Peer db - embedded or couch
- [ ] Custom endorsement policy
- [ ] Post generate hook
- [ ] Channel query scripts
- [ ] Orderer sharding
- [ ] Fabric in versions lower than 2.0
- [ ] Blockchain explorer (won't be supported)
- [ ] Monitoring - log level
- [ ] Fablo REST (won't be supported?)
- [ ] Number of peer instances
- [ ] Number of anchor peer instances
- [ ] Number of orderer instances
- [ ] Private data collections
- [ ] Setting versions of CA, HLF etc on Kubernetes Operators @dzikowski https://github.com/hyperledger-labs/fablo/pull/373

Additional tasks:
- [ ] Update default CA to 1.5.5 @dzikowski https://github.com/hyperledger-labs/fablo/pull/373
- [ ] Create script for building Fabric images for Apple M1 (`./fablo build-images <arm64>`) @dzikowski

**Comment by shivaabhishek07** [comment]
Hey @dzikowski , I want to work on this aspect and improve Kubernetes operators support for Fablo. I have applied LFX mentorship program for the term June-Nov 2023.
Hope you look into my application and get accepted!
I want guidance on what I have to do.

**Comment by dzikowski** [comment]
Basic, experimental support added in Fablo 1.2.0. This is a subject of further testing and improvements in separate issues
